# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Hackboat 2025
email: hackboat@bsidespdx.org
description: >- # this means to ignore newlines until "baseurl:"
  Hackboat 2025 - An infosec unconference on the high seas.
baseurl: '/hackboat2025' # the subpath of your site, e.g. /blog
url: 'https://kwicz.github.io' # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: hackboatpdx
twitter_url: https://twitter.com/hackboatpdx
phone: (503) 560 3551
address: 7600 N Interstate Ave Ste. 210, Portland, OR USA

# Build settings
theme: minima
plugins:
  - jekyll-feed
destination: docs

# Custom settings
event_date: June 6th, 2025
event_location: 110 SE Caruthers St, Portland, Oregon, 97214 (by OMSI)
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
